import { MatchEvent, Commentary, DemoScenario } from "./types";

const demoEvents: MatchEvent[] = [
  {
    id: "evt-1",
    type: "kick_off",
    timestamp: 0,
    matchMinute: "0'",
    team: "home",
    description: "경기 시작! 고운동의 킥오프로 전반전이 시작됩니다.",
    importance: "medium",
  },
  {
    id: "evt-2",
    type: "shot",
    timestamp: 8,
    matchMinute: "12'",
    team: "home",
    player: "김철수",
    description: "김철수의 중거리 슛! 골대를 살짝 빗나갑니다.",
    importance: "medium",
  },
  {
    id: "evt-3",
    type: "foul",
    timestamp: 15,
    matchMinute: "23'",
    team: "away",
    player: "박영호",
    description: "박영호에 대한 거친 태클. 프리킥 획득!",
    importance: "low",
  },
  {
    id: "evt-4",
    type: "corner",
    timestamp: 22,
    matchMinute: "31'",
    team: "home",
    description: "고운동 코너킥 기회!",
    importance: "low",
  },
  {
    id: "evt-5",
    type: "goal",
    timestamp: 28,
    matchMinute: "35'",
    team: "home",
    player: "이정민",
    description: "골!!! 이정민의 환상적인 왼발 슛이 골네트를 흔듭니다!",
    importance: "critical",
  },
  {
    id: "evt-6",
    type: "card_yellow",
    timestamp: 36,
    matchMinute: "42'",
    team: "away",
    player: "최동훈",
    description: "최동훈 선수에게 옐로카드! 뒤에서 잡아당기는 반칙.",
    importance: "medium",
  },
  {
    id: "evt-7",
    type: "half_time",
    timestamp: 42,
    matchMinute: "45+2'",
    team: "home",
    description: "전반전 종료! 고운동 1-0 아름동",
    importance: "high",
  },
  {
    id: "evt-8",
    type: "substitution",
    timestamp: 48,
    matchMinute: "46'",
    team: "away",
    player: "한상우",
    description: "아름동 선수 교체. 한상우 투입으로 공격 강화!",
    importance: "medium",
  },
  {
    id: "evt-9",
    type: "save",
    timestamp: 56,
    matchMinute: "58'",
    team: "home",
    description: "골키퍼 윤기태의 슈퍼 세이브! 위기를 모면합니다!",
    importance: "high",
  },
  {
    id: "evt-10",
    type: "goal",
    timestamp: 64,
    matchMinute: "67'",
    team: "away",
    player: "한상우",
    description: "동점골!! 한상우의 헤딩골! 교체 투입 후 바로 득점!",
    importance: "critical",
  },
  {
    id: "evt-11",
    type: "penalty",
    timestamp: 74,
    matchMinute: "78'",
    team: "home",
    description: "페널티킥! 박스 안에서 핸드볼 반칙!",
    importance: "critical",
  },
  {
    id: "evt-12",
    type: "goal",
    timestamp: 80,
    matchMinute: "80'",
    team: "home",
    player: "이정민",
    description: "골!!!! 이정민의 PK 성공! 침착하게 오른쪽 구석으로!",
    importance: "critical",
  },
  {
    id: "evt-13",
    type: "card_red",
    timestamp: 88,
    matchMinute: "88'",
    team: "away",
    player: "정태영",
    description: "퇴장! 정태영 선수 두 번째 경고로 레드카드!",
    importance: "high",
  },
  {
    id: "evt-14",
    type: "full_time",
    timestamp: 94,
    matchMinute: "90+3'",
    team: "home",
    description: "경기 종료! 고운동 2-1 아름동! 이정민 멀티골!",
    importance: "critical",
  },
];

const demoCommentaries: Record<string, Commentary[]> = {
  "evt-1": [
    {
      id: "com-1-1",
      eventId: "evt-1",
      casterId: "caster-pbp",
      text: "자, 드디어 경기가 시작됩니다! 고운동과 아름동의 동네 더비매치! 고운동의 킥오프로 전반전이 시작됩니다! 오늘 날씨도 좋고, 경기하기 딱이네요!",
      timestamp: 0,
      emotion: "excited",
    },
    {
      id: "com-1-2",
      eventId: "evt-1",
      casterId: "caster-analyst",
      text: "고운동은 4-4-2 포메이션으로 출발하네요. 에이스 이정민을 최전방에 배치했고, 중원에는 김철수가 플레이메이커 역할을 맡고 있습니다. 매주 같이 뛰니까 호흡이 좋죠.",
      timestamp: 1,
      emotion: "analytical",
    },
    {
      id: "com-1-3",
      eventId: "evt-1",
      casterId: "caster-entertainer",
      text: "와~ 동네 축구인데 이 분위기 실화입니까? 양쪽 아내분들이 응원하러 오셨는데 볼륨이 프로급이에요! 오늘 진 팀이 치킨 쏜다고 했대요 ㅋㅋ",
      timestamp: 2,
      emotion: "humorous",
    },
  ],
  "evt-2": [
    {
      id: "com-2-1",
      eventId: "evt-2",
      casterId: "caster-pbp",
      text: "김철수가 공을 몰고 올라갑니다! 30미터 밖에서 강슛! 아~~ 아깝게 빗나갑니다! 골대 오른쪽으로 살짝!",
      timestamp: 8,
      emotion: "excited",
    },
    {
      id: "com-2-2",
      eventId: "evt-2",
      casterId: "caster-analyst",
      text: "김철수 선수, 대학교 때 축구부 출신이라 슈팅 자세가 확실히 다릅니다. 패스 대신 직접 슈팅을 선택한 판단이 나쁘지 않았어요. 방향만 좀 더 왼쪽이었으면요.",
      timestamp: 9,
      emotion: "analytical",
    },
  ],
  "evt-3": [
    {
      id: "com-3-1",
      eventId: "evt-3",
      casterId: "caster-pbp",
      text: "박영호가 드리블 돌파를 시도하는데... 앗! 뒤에서 거친 태클이 들어왔습니다! 심판 호각을 불고, 프리킥을 줍니다!",
      timestamp: 15,
      emotion: "tense",
    },
    {
      id: "com-3-3",
      eventId: "evt-3",
      casterId: "caster-entertainer",
      text: "야~ 동네 축구에서 그렇게 세게 밀면 어떡해요! 다음 주에도 같이 축구해야 할 사이인데 ㅋㅋ 심판도 옆집 아저씨시잖아요~",
      timestamp: 16,
      emotion: "humorous",
    },
  ],
  "evt-4": [
    {
      id: "com-4-1",
      eventId: "evt-4",
      casterId: "caster-pbp",
      text: "고운동 코너킥! 김철수가 코너 지역으로 향합니다. 중요한 세트피스 기회입니다!",
      timestamp: 22,
      emotion: "neutral",
    },
  ],
  "evt-5": [
    {
      id: "com-5-1",
      eventId: "evt-5",
      casterId: "caster-pbp",
      text: "코너킥에서 이어진 플레이! 이정민이 왼쪽에서 받아서— 컷 인! 슈팅!! 골~~~~~~!!!! 골입니다!!!! 이정민!!!!! 환상적인 왼발 슛!!!!",
      timestamp: 28,
      emotion: "excited",
    },
    {
      id: "com-5-2",
      eventId: "evt-5",
      casterId: "caster-analyst",
      text: "이정민 선수, 동네 축구에서 이런 골이 나올 줄이야. 왼쪽에서 안쪽으로 들어오면서 왼발로 감아 찬 건데요. 평소에 매일 퇴근 후 연습장에서 혼자 연습한다더니 결과가 나오네요.",
      timestamp: 29,
      emotion: "analytical",
    },
    {
      id: "com-5-3",
      eventId: "evt-5",
      casterId: "caster-entertainer",
      text: "우와~!!! 이게 동네 축구 맞습니까?! 이정민 씨, 회사원 맞아요?! 골키퍼 표정 보세요 ㅋㅋ 완전 멘붕이에요! 아 진짜 이 맛에 동네 축구 하는 겁니다 여러분!!",
      timestamp: 30,
      emotion: "humorous",
    },
  ],
  "evt-6": [
    {
      id: "com-6-1",
      eventId: "evt-6",
      casterId: "caster-pbp",
      text: "최동훈 선수에게 옐로카드가 나왔습니다! 뒤에서 유니폼을 잡아당기는 반칙이었네요.",
      timestamp: 36,
      emotion: "neutral",
    },
    {
      id: "com-6-2",
      eventId: "evt-6",
      casterId: "caster-analyst",
      text: "역습 상황을 끊기 위한 전술적 파울이에요. 동네 축구에서도 이런 영리한 플레이가 나오네요. 다만 후반에 조심해야 합니다. 퇴장당하면 다음 주 경기도 못 뛰거든요.",
      timestamp: 37,
      emotion: "analytical",
    },
  ],
  "evt-7": [
    {
      id: "com-7-1",
      eventId: "evt-7",
      casterId: "caster-pbp",
      text: "전반전이 끝났습니다! 고운동 1대 0으로 리드! 이정민의 멋진 골이 전반전의 하이라이트였죠!",
      timestamp: 42,
      emotion: "excited",
    },
    {
      id: "com-7-2",
      eventId: "evt-7",
      casterId: "caster-analyst",
      text: "전반전 고운동이 경기를 지배했습니다. 아름동은 후반에 분명히 변화를 줄 겁니다. 하프타임에 아이스크림 사오신다던 부인분이 전술 코칭도 해주시겠죠.",
      timestamp: 43,
      emotion: "analytical",
    },
    {
      id: "com-7-3",
      eventId: "evt-7",
      casterId: "caster-entertainer",
      text: "하프타임! 옆에서 파시는 어묵 사먹기 딱 좋은 타이밍인데요? ㅋㅋ 전반전 MVP는 이정민이지만, 골대 뒤에서 응원하시는 이정민 아내분에게도 어시스트 드리고 싶습니다!",
      timestamp: 44,
      emotion: "humorous",
    },
  ],
  "evt-8": [
    {
      id: "com-8-1",
      eventId: "evt-8",
      casterId: "caster-pbp",
      text: "아름동 선수 교체! 한상우가 투입됩니다! 공격수를 추가하면서 승부를 걸어오는군요!",
      timestamp: 48,
      emotion: "neutral",
    },
    {
      id: "com-8-2",
      eventId: "evt-8",
      casterId: "caster-analyst",
      text: "한상우 선수는 키가 185에 제공력이 좋은 선수입니다. 평소 농구도 하시는 분이라 크로스 공격을 강화하려는 의도네요. 고운동 수비진이 공중볼에 집중해야 합니다.",
      timestamp: 49,
      emotion: "analytical",
    },
  ],
  "evt-9": [
    {
      id: "com-9-1",
      eventId: "evt-9",
      casterId: "caster-pbp",
      text: "아름동의 슈팅이 들어옵니다! 윤기태!! 슈퍼 세이브!!! 한 손으로 걷어냈습니다!! 위기를 넘겼습니다!",
      timestamp: 56,
      emotion: "excited",
    },
    {
      id: "com-9-2",
      eventId: "evt-9",
      casterId: "caster-analyst",
      text: "윤기태 선수가 고등학교 때 핸드볼 하셨다더니 역시 순발력이 남다릅니다. 니어포스트 방향 강슛을 왼손 끝으로 걷어낸 건 정말 대단해요.",
      timestamp: 57,
      emotion: "analytical",
    },
    {
      id: "com-9-3",
      eventId: "evt-9",
      casterId: "caster-entertainer",
      text: "윤기태 씨 방금 스파이더맨이었나요?! 동네 축구 골키퍼가 이렇게 잘하면 반칙 아닙니까?! 아름동 선수들 표정이 '이걸 막는다고?' ㅋㅋ",
      timestamp: 58,
      emotion: "humorous",
    },
  ],
  "evt-10": [
    {
      id: "com-10-1",
      eventId: "evt-10",
      casterId: "caster-pbp",
      text: "크로스가 올라갑니다! 한상우! 헤딩!!! 들어갔습니다!!! 동점골!!! 1대 1!!! 교체 투입된 한상우가 해냈습니다!!!",
      timestamp: 64,
      emotion: "excited",
    },
    {
      id: "com-10-2",
      eventId: "evt-10",
      casterId: "caster-analyst",
      text: "팀장의 교체 카드가 적중했습니다. 한상우 선수의 키를 활용한 헤딩골이네요. 수비수 사이를 파고들며 타이밍 좋게 헤딩을 연결했어요.",
      timestamp: 65,
      emotion: "analytical",
    },
    {
      id: "com-10-3",
      eventId: "evt-10",
      casterId: "caster-entertainer",
      text: "한상우 선수, 교체 투입 후 20분 만에 골이라니! 벤치에서 에너지 드링크 드시고 나온 거예요?! 아름동 쪽에서 '우리도 할 수 있다' 소리가 들립니다!",
      timestamp: 66,
      emotion: "humorous",
    },
  ],
  "evt-11": [
    {
      id: "com-11-1",
      eventId: "evt-11",
      casterId: "caster-pbp",
      text: "심판이 달려갑니다! 호각을 불고... 페널티킥!!! 페널티킥을 선언합니다!!! 박스 안에서 핸드볼 반칙!!!",
      timestamp: 74,
      emotion: "excited",
    },
    {
      id: "com-11-2",
      eventId: "evt-11",
      casterId: "caster-analyst",
      text: "크로스가 올라올 때 수비수의 팔이 부자연스럽게 올라가 있었어요. 동네 축구 심판이지만 정확한 판정입니다. 이건 페널티가 맞아요.",
      timestamp: 75,
      emotion: "analytical",
    },
    {
      id: "com-11-3",
      eventId: "evt-11",
      casterId: "caster-entertainer",
      text: "이럴 때 제일 긴장되는 게... 누가 차느냐! 이정민이 공을 잡았어요... 아름동 골키퍼 표정이 벌써 불안합니다... 옆에서 구경하시는 할머니도 긴장하시네요!",
      timestamp: 76,
      emotion: "tense",
    },
  ],
  "evt-12": [
    {
      id: "com-12-1",
      eventId: "evt-12",
      casterId: "caster-pbp",
      text: "이정민이 공을 올려놓습니다... 짧은 도움닫기... 차다!! 골!!!!!!! 역전골!!!!!!! 이정민!!!! 침착하게 오른쪽 구석으로!! 2대 1!!!",
      timestamp: 80,
      emotion: "excited",
    },
    {
      id: "com-12-2",
      eventId: "evt-12",
      casterId: "caster-analyst",
      text: "대단한 멘탈입니다. 동네 축구에서 이 압박감 속에 골키퍼의 움직임을 끝까지 보고 반대 방향으로 찼어요. 이정민 선수, 평소 직장에서도 이렇게 침착하시면 승진 각이에요.",
      timestamp: 81,
      emotion: "analytical",
    },
    {
      id: "com-12-3",
      eventId: "evt-12",
      casterId: "caster-entertainer",
      text: "멀~티~골~~~~!!! 이정민의 원맨쇼입니다!!! 오늘 치킨값은 아름동이 내는 걸로 확정! 이정민 아내분이 폰으로 영상 찍고 계시네요 ㅋㅋ 인스타 올리시겠죠?!",
      timestamp: 82,
      emotion: "humorous",
    },
  ],
  "evt-13": [
    {
      id: "com-13-1",
      eventId: "evt-13",
      casterId: "caster-pbp",
      text: "정태영 선수에게 두 번째 경고! 레드카드입니다!! 아름동 10명으로 남은 시간을 보내야 합니다!",
      timestamp: 88,
      emotion: "tense",
    },
    {
      id: "com-13-2",
      eventId: "evt-13",
      casterId: "caster-analyst",
      text: "감정 조절에 실패한 겁니다. 이미 옐로카드를 받은 상태에서 불필요한 반칙을 범했어요. 다음 주 경기도 출장정지인데... 술자리에서 좀 들을 수 있겠네요.",
      timestamp: 89,
      emotion: "analytical",
    },
  ],
  "evt-14": [
    {
      id: "com-14-1",
      eventId: "evt-14",
      casterId: "caster-pbp",
      text: "경기 종료!!!! 고운동 2대 1 아름동!!! 짜릿한 역전승을 거둡니다!!! 이정민의 멀티골로 승리!!!",
      timestamp: 94,
      emotion: "excited",
    },
    {
      id: "com-14-2",
      eventId: "evt-14",
      casterId: "caster-analyst",
      text: "고운동이 후반전 위기를 잘 넘기고 승리했습니다. 이정민의 개인기가 돋보였지만, 윤기태의 슈퍼 세이브와 팀 전체의 조직력도 승리의 핵심이었습니다. 다음 주 경기도 기대됩니다.",
      timestamp: 95,
      emotion: "analytical",
    },
    {
      id: "com-14-3",
      eventId: "evt-14",
      casterId: "caster-entertainer",
      text: "이겼다~~~~!!!! 여러분 오늘 경기 어떠셨습니까?! AI 해설진과 함께한 동네 축구! BoomCast가 더 재밌지 않았습니까?! 지는 팀 치킨 사기로 했으니 아름동 팀원분들 카드 준비하세요~ ㅋㅋ 다음 주에도 BoomCast와 함께!",
      timestamp: 96,
      emotion: "humorous",
    },
  ],
};

export const demoScenario: DemoScenario = {
  id: "demo-neighborhood-2026",
  title: "동네 더비: 고운동 vs 아름동",
  description: "동네 일반인들의 짜릿한 주말 축구 경기! AI가 프로급으로 중계합니다",
  match: {
    homeTeam: "고운동",
    awayTeam: "아름동",
    homeScore: 2,
    awayScore: 1,
    currentMinute: "90+3'",
    status: "full_time",
    events: demoEvents,
  },
  events: demoEvents,
  commentaries: demoCommentaries,
};

export function getEventIcon(type: MatchEvent["type"]): string {
  const icons: Record<string, string> = {
    goal: "⚽",
    foul: "🦶",
    corner: "🚩",
    offside: "🏳️",
    save: "🧤",
    shot: "💨",
    card_yellow: "🟨",
    card_red: "🟥",
    substitution: "🔄",
    half_time: "⏸️",
    full_time: "🏁",
    kick_off: "▶️",
    free_kick: "🎯",
    penalty: "⭕",
  };
  return icons[type] || "📌";
}

export function getImportanceColor(importance: MatchEvent["importance"]): string {
  const colors: Record<string, string> = {
    low: "text-gray-400",
    medium: "text-blue-400",
    high: "text-amber-400",
    critical: "text-red-400",
  };
  return colors[importance];
}
