import { MatchEvent, Commentary, DemoScenario } from "./types";

const demoEvents: MatchEvent[] = [
  {
    id: "evt-1",
    type: "kick_off",
    timestamp: 0,
    matchMinute: "0'",
    team: "home",
    description: "경기 시작! 수원 삼성의 킥오프로 전반전이 시작됩니다.",
    importance: "medium",
  },
  {
    id: "evt-2",
    type: "shot",
    timestamp: 8,
    matchMinute: "12'",
    team: "home",
    player: "김민재",
    description: "김민재의 중거리 슛! 골대를 살짝 빗나갑니다.",
    importance: "medium",
  },
  {
    id: "evt-3",
    type: "foul",
    timestamp: 15,
    matchMinute: "23'",
    team: "away",
    player: "이강인",
    description: "이강인에 대한 거친 태클. 프리킥 획득!",
    importance: "low",
  },
  {
    id: "evt-4",
    type: "corner",
    timestamp: 22,
    matchMinute: "31'",
    team: "home",
    description: "수원 삼성 코너킥 기회!",
    importance: "low",
  },
  {
    id: "evt-5",
    type: "goal",
    timestamp: 28,
    matchMinute: "35'",
    team: "home",
    player: "손흥민",
    description: "골!!! 손흥민의 환상적인 왼발 슛이 골네트를 흔듭니다!",
    importance: "critical",
  },
  {
    id: "evt-6",
    type: "card_yellow",
    timestamp: 36,
    matchMinute: "42'",
    team: "away",
    player: "무라카미",
    description: "무라카미 선수에게 옐로카드! 뒤에서 잡아당기는 반칙.",
    importance: "medium",
  },
  {
    id: "evt-7",
    type: "half_time",
    timestamp: 42,
    matchMinute: "45+2'",
    team: "home",
    description: "전반전 종료! 수원 삼성 1-0 FC 도쿄",
    importance: "high",
  },
  {
    id: "evt-8",
    type: "substitution",
    timestamp: 48,
    matchMinute: "46'",
    team: "away",
    player: "타나카",
    description: "FC 도쿄 선수 교체. 타나카 투입으로 공격 강화!",
    importance: "medium",
  },
  {
    id: "evt-9",
    type: "save",
    timestamp: 56,
    matchMinute: "58'",
    team: "home",
    description: "골키퍼 조현우의 슈퍼 세이브! 위기를 모면합니다!",
    importance: "high",
  },
  {
    id: "evt-10",
    type: "goal",
    timestamp: 64,
    matchMinute: "67'",
    team: "away",
    player: "타나카",
    description: "동점골!! 타나카의 헤딩골! 교체 투입 후 바로 득점!",
    importance: "critical",
  },
  {
    id: "evt-11",
    type: "penalty",
    timestamp: 74,
    matchMinute: "78'",
    team: "home",
    description: "페널티킥! 박스 안에서 핸드볼 반칙!",
    importance: "critical",
  },
  {
    id: "evt-12",
    type: "goal",
    timestamp: 80,
    matchMinute: "80'",
    team: "home",
    player: "손흥민",
    description: "골!!!! 손흥민의 PK 성공! 침착하게 오른쪽 구석으로!",
    importance: "critical",
  },
  {
    id: "evt-13",
    type: "card_red",
    timestamp: 88,
    matchMinute: "88'",
    team: "away",
    player: "사토",
    description: "퇴장! 사토 선수 두 번째 경고로 레드카드!",
    importance: "high",
  },
  {
    id: "evt-14",
    type: "full_time",
    timestamp: 94,
    matchMinute: "90+3'",
    team: "home",
    description: "경기 종료! 수원 삼성 2-1 FC 도쿄! 손흥민 멀티골!",
    importance: "critical",
  },
];

const demoCommentaries: Record<string, Commentary[]> = {
  "evt-1": [
    {
      id: "com-1-1",
      eventId: "evt-1",
      casterId: "caster-pbp",
      text: "자, 드디어 경기가 시작됩니다! 수원 삼성 블루윙즈와 FC 도쿄의 ACL 16강 빅매치! 수원의 킥오프로 전반전이 시작됩니다!",
      timestamp: 0,
      emotion: "excited",
    },
    {
      id: "com-1-2",
      eventId: "evt-1",
      casterId: "caster-analyst",
      text: "수원은 4-3-3 포메이션으로 출발하네요. 손흥민을 좌측 윙에 배치했고, 중앙에는 김민재가 높은 위치를 잡고 있습니다. 공격적인 의도가 분명합니다.",
      timestamp: 1,
      emotion: "analytical",
    },
    {
      id: "com-1-3",
      eventId: "evt-1",
      casterId: "caster-entertainer",
      text: "와~ 오늘 경기장 분위기 실화입니까? 수원 팬들의 응원 볼륨이 스피커 터질 것 같아요! K-리그 팬심은 세계 최강이라니까요 ㅋㅋ",
      timestamp: 2,
      emotion: "humorous",
    },
  ],
  "evt-2": [
    {
      id: "com-2-1",
      eventId: "evt-2",
      casterId: "caster-pbp",
      text: "김민재가 공을 몰고 올라갑니다! 30미터 밖에서 강슛! 아~~ 아깝게 빗나갑니다! 골대 오른쪽으로 살짝!",
      timestamp: 8,
      emotion: "excited",
    },
    {
      id: "com-2-2",
      eventId: "evt-2",
      casterId: "caster-analyst",
      text: "김민재 선수의 패스 대신 직접 슈팅을 선택한 판단이 나쁘지 않았어요. 수비 블록이 형성되기 전에 빈 공간을 노린 건데, 방향만 좀 더 왼쪽이었으면 됐습니다.",
      timestamp: 9,
      emotion: "analytical",
    },
  ],
  "evt-3": [
    {
      id: "com-3-1",
      eventId: "evt-3",
      casterId: "caster-pbp",
      text: "이강인이 드리블 돌파를 시도하는데... 앗! 뒤에서 거친 태클이 들어왔습니다! 심판 호각을 불고, 프리킥을 줍니다!",
      timestamp: 15,
      emotion: "tense",
    },
    {
      id: "com-3-3",
      eventId: "evt-3",
      casterId: "caster-entertainer",
      text: "야~ 이강인 선수 드리블이 너무 좋으니까 결국 잡을 수밖에 없는 거예요. '못 막으면 눕혀라' 전략인데, 심판님 눈은 못 속이죠~",
      timestamp: 16,
      emotion: "humorous",
    },
  ],
  "evt-4": [
    {
      id: "com-4-1",
      eventId: "evt-4",
      casterId: "caster-pbp",
      text: "수원 삼성 코너킥! 이강인이 코너 지역으로 향합니다. 중요한 세트피스 기회입니다!",
      timestamp: 22,
      emotion: "neutral",
    },
  ],
  "evt-5": [
    {
      id: "com-5-1",
      eventId: "evt-5",
      casterId: "caster-pbp",
      text: "코너킥에서 이어진 플레이! 손흥민이 왼쪽에서 받아서— 컷 인! 슈팅!! 골~~~~~~!!!! 골입니다!!!! 손흥민!!!!! 환상적인 왼발 슛이 오른쪽 상단 구석에 꽂혔습니다!!!!",
      timestamp: 28,
      emotion: "excited",
    },
    {
      id: "com-5-2",
      eventId: "evt-5",
      casterId: "caster-analyst",
      text: "이건 정말 교과서적인 컷인 슈팅입니다. 왼쪽에서 안쪽으로 들어오면서 오른발 수비수를 앞에 두고 왼발로 감아 찬 건데요. 골키퍼가 역방향으로 움직인 것도 있지만, 슈팅 궤적 자체가 수비 불가능한 코스였습니다.",
      timestamp: 29,
      emotion: "analytical",
    },
    {
      id: "com-5-3",
      eventId: "evt-5",
      casterId: "caster-entertainer",
      text: "손-세-이-셔-널~!!! 이게 바로 월드클래스죠!!! 골키퍼: 왼쪽이겠지? 손흥민: ㄴㄴ 오른쪽 ㅋ 아 진짜 이 맛에 축구 보는 겁니다 여러분!!",
      timestamp: 30,
      emotion: "humorous",
    },
  ],
  "evt-6": [
    {
      id: "com-6-1",
      eventId: "evt-6",
      casterId: "caster-pbp",
      text: "무라카미 선수에게 옐로카드가 나왔습니다! 뒤에서 유니폼을 잡아당기는 반칙이었네요.",
      timestamp: 36,
      emotion: "neutral",
    },
    {
      id: "com-6-2",
      eventId: "evt-6",
      casterId: "caster-analyst",
      text: "전술적 파울이에요. 수원의 역습 상황을 끊기 위한 의도적인 반칙인데, 옐로카드를 감수하더라도 실점을 막으려는 판단입니다. 다만 후반에 조심해야겠죠.",
      timestamp: 37,
      emotion: "analytical",
    },
  ],
  "evt-7": [
    {
      id: "com-7-1",
      eventId: "evt-7",
      casterId: "caster-pbp",
      text: "전반전이 끝났습니다! 수원 삼성 1대 0으로 리드하고 있습니다! 손흥민의 멋진 골이 전반전의 하이라이트였죠!",
      timestamp: 42,
      emotion: "excited",
    },
    {
      id: "com-7-2",
      eventId: "evt-7",
      casterId: "caster-analyst",
      text: "전반전 점유율 수원 58%, 도쿄 42%입니다. 수원이 경기를 지배하고 있지만, 도쿄도 후반에 분명히 변화를 줄 겁니다. 감독의 하프타임 전술 수정이 관건이 될 것 같습니다.",
      timestamp: 43,
      emotion: "analytical",
    },
    {
      id: "com-7-3",
      eventId: "evt-7",
      casterId: "caster-entertainer",
      text: "하프타임! 치킨 시키기 딱 좋은 타이밍인데요? 전반전 MVP는 당연히 손흥민이지만, 저는 개인적으로 경기장 치어리더에게도 MVP를 주고 싶습니다 ㅋㅋ",
      timestamp: 44,
      emotion: "humorous",
    },
  ],
  "evt-8": [
    {
      id: "com-8-1",
      eventId: "evt-8",
      casterId: "caster-pbp",
      text: "FC 도쿄 선수 교체! 타나카가 투입됩니다! 공격수를 추가하면서 승부를 걸어오는군요!",
      timestamp: 48,
      emotion: "neutral",
    },
    {
      id: "com-8-2",
      eventId: "evt-8",
      casterId: "caster-analyst",
      text: "예상했던 교체입니다. 타나카는 제공력이 좋은 선수라 크로스 공격을 강화하려는 의도네요. 수원 수비진이 공중볼에 더 집중해야 할 겁니다.",
      timestamp: 49,
      emotion: "analytical",
    },
  ],
  "evt-9": [
    {
      id: "com-9-1",
      eventId: "evt-9",
      casterId: "caster-pbp",
      text: "도쿄의 슈팅이 들어옵니다! 조현우!! 슈퍼 세이브!!! 한 손으로 걷어냈습니다!! 위기를 넘겼습니다!",
      timestamp: 56,
      emotion: "excited",
    },
    {
      id: "com-9-2",
      eventId: "evt-9",
      casterId: "caster-analyst",
      text: "조현우 선수의 반사 신경이 빛나는 순간이었습니다. 니어포스트 방향으로 날아오는 강슛을 왼손 끝으로 걷어낸 건데, 이게 들어갔으면 동점이었어요.",
      timestamp: 57,
      emotion: "analytical",
    },
    {
      id: "com-9-3",
      eventId: "evt-9",
      casterId: "caster-entertainer",
      text: "조현우 선수 방금 스파이더맨이었나요?! 저 반응속도는 사람이 아니라 AI 아닙니까?! 아 맞다, AI는 저희가 합니다 ㅋㅋ",
      timestamp: 58,
      emotion: "humorous",
    },
  ],
  "evt-10": [
    {
      id: "com-10-1",
      eventId: "evt-10",
      casterId: "caster-pbp",
      text: "크로스가 올라갑니다! 타나카! 헤딩!!! 들어갔습니다!!! 동점골!!! 1대 1!!! 교체 투입된 타나카가 해냈습니다!!!",
      timestamp: 64,
      emotion: "excited",
    },
    {
      id: "com-10-2",
      eventId: "evt-10",
      casterId: "caster-analyst",
      text: "감독의 교체 카드가 적중했습니다. 오른쪽에서 올라온 크로스에 타나카가 수비수 사이를 파고들며 타이밍 좋게 헤딩을 연결했어요. 수원 수비가 공중볼 대응에서 허점을 보인 겁니다.",
      timestamp: 65,
      emotion: "analytical",
    },
    {
      id: "com-10-3",
      eventId: "evt-10",
      casterId: "caster-entertainer",
      text: "타나카 선수, 교체 투입 후 20분 만에 골이라니! 벤치에서 뭐 드시고 나온 거예요?! 에너지 드링크?! 아~ 이게 축구의 매력이죠! 뒤집기 드라마!",
      timestamp: 66,
      emotion: "humorous",
    },
  ],
  "evt-11": [
    {
      id: "com-11-1",
      eventId: "evt-11",
      casterId: "caster-pbp",
      text: "심판이 달려갑니다! 호각을 불고... 페널티킥!!! 페널티킥을 선언합니다!!! 박스 안에서 핸드볼 반칙!!!",
      timestamp: 74,
      emotion: "excited",
    },
    {
      id: "com-11-2",
      eventId: "evt-11",
      casterId: "caster-analyst",
      text: "VAR 확인 없이 바로 판정했네요. 크로스가 올라올 때 수비수의 팔이 부자연스럽게 올라가 있었어요. 명백한 핸드볼 반칙입니다. 이건 페널티가 맞습니다.",
      timestamp: 75,
      emotion: "analytical",
    },
    {
      id: "com-11-3",
      eventId: "evt-11",
      casterId: "caster-entertainer",
      text: "이럴 때 제일 긴장되는 게... 누가 차느냐! 화면에 잡히는 손흥민의 표정... 눈빛이 무섭다... 이건... 넣을 눈빛입니다!",
      timestamp: 76,
      emotion: "tense",
    },
  ],
  "evt-12": [
    {
      id: "com-12-1",
      eventId: "evt-12",
      casterId: "caster-pbp",
      text: "손흥민이 공을 올려놓습니다... 짧은 도움닫기... 차다!! 골!!!!!!! 역전골!!!!!!! 손흥민!!!! 침착하게 오른쪽 구석으로!! 골키퍼 반대편!!! 2대 1!!!",
      timestamp: 80,
      emotion: "excited",
    },
    {
      id: "com-12-2",
      eventId: "evt-12",
      casterId: "caster-analyst",
      text: "대단한 멘탈입니다. 이 압박 상황에서 골키퍼의 움직임을 끝까지 보고 반대 방향으로 찼어요. 페널티킥 성공률이 높은 이유가 바로 이런 침착함에 있습니다. 경기 경험에서 나오는 클러치 능력이죠.",
      timestamp: 81,
      emotion: "analytical",
    },
    {
      id: "com-12-3",
      eventId: "evt-12",
      casterId: "caster-entertainer",
      text: "멀~티~골~~~~!!! 손흥민의 원맨쇼입니다!!! 저도 모르게 소리 질렀어요!!! 이 순간을 위해 태어난 사람!! 오늘 치킨은 손흥민이 쏘는 걸로!! (아님 말고 ㅋ)",
      timestamp: 82,
      emotion: "humorous",
    },
  ],
  "evt-13": [
    {
      id: "com-13-1",
      eventId: "evt-13",
      casterId: "caster-pbp",
      text: "사토 선수에게 두 번째 경고! 레드카드입니다!! FC 도쿄 10명으로 남은 시간을 보내야 합니다!",
      timestamp: 88,
      emotion: "tense",
    },
    {
      id: "com-13-2",
      eventId: "evt-13",
      casterId: "caster-analyst",
      text: "감정 조절에 실패한 결과입니다. 이미 옐로카드를 받은 상태에서 불필요한 반칙을 범했어요. 팀으로선 치명적인 수적 열세가 됐습니다.",
      timestamp: 89,
      emotion: "analytical",
    },
  ],
  "evt-14": [
    {
      id: "com-14-1",
      eventId: "evt-14",
      casterId: "caster-pbp",
      text: "경기 종료!!!! 수원 삼성 2대 1 FC 도쿄!!! ACL 16강에서 짜릿한 역전승을 거둡니다!!! 손흥민의 멀티골로 8강 진출!!!",
      timestamp: 94,
      emotion: "excited",
    },
    {
      id: "com-14-2",
      eventId: "evt-14",
      casterId: "caster-analyst",
      text: "수원이 후반전 위기를 잘 넘기고 결국 승리를 가져갔습니다. 손흥민의 개인 능력이 돋보였지만, 조현우의 슈퍼 세이브와 팀 전체의 전술적 안정감도 승리의 핵심 요인이었습니다. 다음 8강이 기대됩니다.",
      timestamp: 95,
      emotion: "analytical",
    },
    {
      id: "com-14-3",
      eventId: "evt-14",
      casterId: "caster-entertainer",
      text: "이겼다~~~~!!!! 여러분 오늘 경기 어떠셨습니까?! AI 해설진과 함께한 90분! 저희 BoomCast가 더 재밌지 않았습니까?! 다음 경기도 BoomCast와 함께! 치킨 먹으면서 또 봐요~! 🍗⚽",
      timestamp: 96,
      emotion: "humorous",
    },
  ],
};

export const demoScenario: DemoScenario = {
  id: "demo-acl-2026",
  title: "ACL 16강: 수원 삼성 vs FC 도쿄",
  description: "손흥민의 멀티골로 역전승을 거두는 짜릿한 ACL 16강 경기",
  match: {
    homeTeam: "수원 삼성",
    awayTeam: "FC 도쿄",
    homeScore: 2,
    awayScore: 1,
    currentMinute: "90+3'",
    status: "full_time",
    events: demoEvents,
  },
  events: demoEvents,
  commentaries: demoCommentaries,
};

export function getEventIcon(type: MatchEvent["type"]): string {
  const icons: Record<string, string> = {
    goal: "⚽",
    foul: "🦶",
    corner: "🚩",
    offside: "🏳️",
    save: "🧤",
    shot: "💨",
    card_yellow: "🟨",
    card_red: "🟥",
    substitution: "🔄",
    half_time: "⏸️",
    full_time: "🏁",
    kick_off: "▶️",
    free_kick: "🎯",
    penalty: "⭕",
  };
  return icons[type] || "📌";
}

export function getImportanceColor(importance: MatchEvent["importance"]): string {
  const colors: Record<string, string> = {
    low: "text-gray-400",
    medium: "text-blue-400",
    high: "text-amber-400",
    critical: "text-red-400",
  };
  return colors[importance];
}
